name: Tag on Merge

on:
  push:
    branches:
      - master
      
permissions:
  contents: write

jobs:
  add-tag:
    runs-on: macos-12
    strategy:
    matrix:
      platform:
          - macOS
          - watchOS
          - tvOS
          - iOS
          - mac-catalyst
          
    steps:
      - name: Check out code
        uses: actions/checkout@v3 

      # - name: Setup Xcode
      #   uses: maxim-lobanov/setup-xcode@v1
      #   with:
      #     xcode-version: '14.2.0'
        
      - name: Setup xcodebuild
        uses: mxcl/xcodebuild@v1
        with:
          platform: ${{ matrix.platform }}
          
      - name: Get Bundle Version
        id: bundle_version
        run: |
          bundle_version=$(xcodebuild -showBuildSettings | grep MARKETING_VERSION | tr -d 'MARKETING_VERSION =')
          # echo "::set-output name=version::${bundle_version}"
          echo "version=${bundle_version}" >> "$GITHUB_ENV"
      
      - name: Add Tag
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git tag -a "v${{ steps.bundle_version.outputs.version }}" -m "Version ${{ steps.bundle_version.outputs.version }}"
          git push origin "v${{ steps.bundle_version.outputs.version }}"
