name: Tag on Merge

on:
  push:
    branches:
      - master
      
permissions:
  contents: write

jobs:
  add-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        
      - name: Setup xcodebuild
        uses: mxcl/xcodebuild@v1
          
      - name: Get Bundle Version
        #uses: mxcl/xcodebuild@v1
        id: bundle_version
        run: |
          bundle_version=$(xcodebuild -showBuildSettings | grep MARKETING_VERSION | tr -d 'MARKETING_VERSION =')
          # echo "::set-output name=version::${bundle_version}"
          echo "version=${bundle_version}" >> "$GITHUB_ENV"
      
      - name: Add Tag
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git tag -a "v${{ steps.bundle_version.outputs.version }}" -m "Version ${{ steps.bundle_version.outputs.version }}"
          git push origin "v${{ steps.bundle_version.outputs.version }}"
